language: ruby
before_install:
  - gem install bundler
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - cp config/settings.yml{.example,}
  - cp config/database.yml{.example,}
  - bundle exec rake db:setup
rvm:
  - 2.1.1
branches:
  only:
    - master
cache: bundler
